name: Deploy to Cloud Run

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: project-with-cka 
  REGION: us-central1
  SERVICE_NAME: cloudrun-demo
  REPO_NAME: cloudrun-repo

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v4
      
      - name: authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
           workload_identity_provider: projects/818786073643/locations/global/workloadIdentityPools/github-pool/providers/github-provider        service_account: github-sa@project-with-cka.iam.gserviceaccount.com


      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Build and Push Image
        run: |
          gcloud build submit \
            --tag ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${SERVICE_NAME}:${{ github.sha }}

      - name: Deploy to cloud run 
        run: |
           gcloud run deploy ${SERVICE_NAME} --image ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${SERVICE_NAME}:${{ github.sha }} --region ${REGION} --platform managed --allow-unauthenticated

